spring:
  application:
    name: msmanager
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/manager_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    packages-to-scan: com.bantads.entity
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false

server:
  port: 8084

services:
  ms-client:
    base-url: http://${MS_CLIENT_HOST:ms-client}:${MS_CLIENT_PORT:8082}
  ms-account:
    base-url: http://${MS_ACCOUNT_HOST:ms-account}:${MS_ACCOUNT_PORT:8083}
