hibernate.hbm2ddl.auto=update
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jdbc.driverClassName=org.postgresql.Driver
jdbc.user=user
jdbc.pass=password

command.jdbc.url=jdbc:postgresql://postgres-db:5432/command_db
request.jdbc.url=jdbc:postgresql://postgres-db:5432/request_db
